# Generated by Django 5.2.2 on 2025-06-09 05:17

import books.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the book",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=200),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the book", max_length=100),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="ISBN-10 or ISBN-13 of the book",
                        max_length=17,
                        unique=True,
                        validators=[books.models.validate_isbn],
                    ),
                ),
                (
                    "published_year",
                    models.PositiveIntegerField(
                        help_text="Year the book was published",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1000, message="Published year must be at least 1000"
                            ),
                            django.core.validators.MaxValueValidator(
                                2025, message="Published year cannot be more than 2025"
                            ),
                        ],
                    ),
                ),
                (
                    "genre",
                    models.CharField(help_text="Genre of the book", max_length=50),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the book in USD",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Price must be at least $0.01"
                            )
                        ],
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of books in stock"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the book",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the book was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the book was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
                ],
            },
        ),
    ]
